version: '3.8'

services:
  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: